--require "user.coc" -- uwu
require "user.npairs"
-- require "user.nvim-tree"
require "user.treesitter"
-- require "user.toggleterm"
require "user.colorizer"
require "user.comment"
-- require "user.lualine"
require "user.crates"
require "user.rust-tools"
require "user.trouble"
require "user.fidget"
--require "user.hop"
--require "user.mason"
--require "user.null-ls"

