#! /bin/sh


$HOME/.on_start.sh

bspc monitor DVI-D-0   -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-A-3  -d I II III IV V VI VII VIII IX X

bspc config bottom_padding	     0
bspc config border_width        4
bspc config window_gap          0	
bspc config top_padding		     31

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config focus_follows_pointer true


#bspc rule -a Gimp state=floating follow=on
#bspc rule -a firefox desktop='^8'
#bspc rule -a discord desktop='^9'


baspc rule -a NT Godot_Engine state=floating follow=on

bspc config focus_followsn_pointer    true

