#! /bin/sh


$HOME/.on_start.sh

bspc monitor DVI-D-0 -d  III IV V VI VII VIII IX X
bspc monitor HDMI-A-3 -d I II

bspc config bottom_padding	3
bspc config border_width        5
bspc config window_gap          0	
bspc config top_padding		24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a discord desktop='^2'


bspc config focus_followsn_pointer    true

